/* !
@file       glpbo.h
@author     pghali@digipen.edu
@co-author  parminder.singh@digipen.edu
@co-author  c.chiow@digipen.edu
@date       28/06/2024
@modified   17/06/2026

This file contains the declaration of structure GLPbo that encapsulates the
functionality required to stream images generated by a 3D graphics pipe
emulator executed on the CPU for display by the GPU.

Changes from Tutorial 6:
- Added GLPbo::Model struct to hold OBJ mesh data (positions, normals, tex,
  triangle indices, and transformed window-coordinate positions).
- Added static data members: mdl_ref (current model), render_mode,
  rotate_angle, culled_cnt, is_painter_mode, painter_dragging,
  painter_start, painter_end, models vector.
- Declared viewport_xform(), set_pixel(), render_linebresenham(),
  render_triangle() (flat overload), render_triangle() (smooth overload),
  painter_mode(), setup_quad_vao(), setup_shdrpgm().

*//*__________________________________________________________________________*/

#ifndef GLPBO_H
#define GLPBO_H

/*                                                                   includes
----------------------------------------------------------------------------- */
#include <GL/glew.h>
#include <glslshader.h>
#include <glm/glm.hpp>
#include <vector>
#include <string>

/*  _________________________________________________________________________ */
struct GLPbo
{
    // forward declaration
    union Color;

    // -----------------------------------------------------------------------
    // Model: stores geometry returned by DPML::parse_obj_mesh
    // -----------------------------------------------------------------------
    struct Model
    {
        std::string     name;   // model name (prefix of OBJ filename)
        std::vector<glm::vec3> pm;  // invariant NDC positions
        std::vector<glm::vec3> nml; // per-vertex normals mapped to [0,1] RGB
        std::vector<glm::vec2> tex; // texture coords (unused this submission)
        std::vector<unsigned short> tri; // triangle index list (3 per tri)
        std::vector<glm::vec3> pd;  // window-space positions after xform
    };

    // -----------------------------------------------------------------------
    // Static member function declarations
    // -----------------------------------------------------------------------

    // Per-frame emulator: maps PBO, fills pixels, uploads to texture
    static void emulate();

    // Renders textured full-window quad and updates title bar
    static void draw_fullwindow_quad();

    // Init / cleanup
    static void init(GLsizei w, GLsizei h);
    static void setup_quad_vao();
    static void setup_shdrpgm();
    static void cleanup();

    // Viewport transform: rotation about z-axis then NDC -> window coords
    // Fills model.pd from model.pm using rotate_angle and window dimensions.
    static void viewport_xform(Model& model);

    // Write a single RGBA pixel at window coordinate (x, y).
    // Implements scissoring against the full window rectangle.
    static void set_pixel(GLint x, GLint y, GLPbo::Color clr);

    // Bresenham integer-only line rasterizer
    static void render_linebresenham(GLint px0, GLint py0,
        GLint px1, GLint py1,
        GLPbo::Color draw_clr);

    // Flat-shaded triangle rasterizer (edge equations + top-left rule).
    // Returns false if triangle is back-facing (culled).
    static bool render_triangle(glm::vec3 const& p0,
        glm::vec3 const& p1,
        glm::vec3 const& p2,
        glm::vec3 const& clr);

    // Smooth-shaded triangle rasterizer (edge equations + barycentric interp).
    // Returns false if triangle is back-facing (culled).
    static bool render_triangle(glm::vec3 const& p0,
        glm::vec3 const& p1,
        glm::vec3 const& p2,
        glm::vec3 const& c0,
        glm::vec3 const& c1,
        glm::vec3 const& c2);

    // Painter mode: called from emulate() when is_painter_mode is true
    static void painter_mode();

    // Clear-color helpers (akin to glClearColor / glClear)
    static void set_clear_color(GLPbo::Color c);
    static void set_clear_color(GLubyte r, GLubyte g, GLubyte b,
        GLubyte a = 255);
    static void clear_color_buffer();

    // -----------------------------------------------------------------------
    // Static data members
    // -----------------------------------------------------------------------

    // Dimensions & derived counts
    static GLsizei width, height;
    static GLsizei pixel_cnt, byte_cnt;

    // PBO mapped pointer (valid only between Map/Unmap)
    static Color* ptr_to_pbo;

    // OpenGL object handles
    static GLuint vaoid;
    static GLuint elem_cnt;
    static GLuint pboid;
    static GLuint texid;
    static GLSLShader shdr_pgm;

    // Clear colour
    static Color clear_clr;

    // Scene models
    static std::vector<Model> models;
    static int mdl_ref;        // index of currently displayed model

    // Render mode:
    //   0 = wireframe black
    //   1 = wireframe random-color per edge
    //   2 = flat shaded (random color per triangle)
    //   3 = smooth shaded (interpolated normals-as-colors)
    static int render_mode;

    // Rotation angle (degrees) for z-axis rotation; incremented by key R
    static float rotate_angle;

    // Count of back-face-culled triangles in the current frame
    static int culled_cnt;

    // Painter mode state
    // @modified 30/06/2026 c.chiow@digipen.edu
    // Implements freehand drawing to match the sample executable: while
    // the LMB is held, every mouse-move event commits a short Bresenham
    // segment from the last processed point (painter_prev) to the new
    // cursor position directly into painter_canvas. Chaining many short
    // segments together produces a continuous curve that follows the
    // cursor's actual path, not just a single straight chord from
    // press-point to release-point.
    static bool is_painter_mode;
    static bool painter_dragging;     // true while LMB is held down
    static glm::ivec2 painter_start;  // recorded on LMB press (stroke origin)
    static glm::ivec2 painter_end;    // most recent committed point
    static glm::ivec2 painter_prev;   // last point a segment was drawn from
    // CPU-side persistent canvas holding all committed strokes.
    // Every painter-mode frame copies this into the PBO unchanged; all
    // actual drawing happens directly into this canvas as the mouse moves.
    static std::vector<Color> painter_canvas;

    // -----------------------------------------------------------------------
    // Color union
    // -----------------------------------------------------------------------
    union Color
    {
        struct { GLubyte r, g, b, a; };
        GLubyte val[4];
        GLuint  raw;

        Color(GLubyte re = 0, GLubyte gr = 0,
            GLubyte bl = 0, GLubyte al = 255)
            : r(re), g(gr), b(bl), a(al) {
        }
    };
};

#endif /* GLPBO_H */